name: Bug Report 🐛
description: Find a bug? File a bug report!
title: "Bug Report:"
labels: ["bug", "needs triage"]
assignees: Timthreetwelve
body:
  - type: markdown
    attributes:
      value: "⬆️ Feel free to change the issue title above ⬆️"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues (both open and closed).
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened or didn't happen?
      description: Describe what happened.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Running as Administrator
        4. See error...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version the app are you running?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: input
    id: windows-version
    attributes:
      label: Windows Version
      description: What version of Windows are you running? Include the build number if possible.
      placeholder: ex. Windows 11 22H2 build 22621.1702
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste (or attach) any relevant log output.

        You can open the application log file by clicking on the three dot menu in the upper right and selecting View Log File.
        If the error occurred during installation, paste the setup log (found in the %Temp% directory). The file name will look like *Setup Log date sequence#.txt*
      render: shell
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give me more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
